<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CodeImp.DoomBuilder.UDBScript</RootNamespace>
    <AssemblyName>UDBScript</AssemblyName>
    <OutputPath>..\..\Build\Plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Builder.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\BuilderModes\BuilderModes.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Jint" />
    <PackageReference Include="Esprima" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Actions.cfg" />
    <EmbeddedResource Include="Resources\Folder.png" />
    <EmbeddedResource Include="Resources\Script.png" />
    <EmbeddedResource Include="Resources\SearchClear.png" />
  </ItemGroup>
</Project>
