<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ThreeDFloorMode</RootNamespace>
    <AssemblyName>ThreeDFloorMode</AssemblyName>
    <OutputPath>..\..\Build\Plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Builder.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\BuilderEffects\BuilderEffects.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\BuilderModes\BuilderModes.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Actions.cfg" />
    <EmbeddedResource Include="Resources\ThreeDFloorIcon.png" />
    <EmbeddedResource Include="Resources\SlopeModeIcon.png" />
    <EmbeddedResource Include="Resources\DrawSlopeModeIcon.png" />
    <EmbeddedResource Include="Resources\Ceiling.png" />
    <EmbeddedResource Include="Resources\Floor.png" />
    <EmbeddedResource Include="Resources\FloorAndCeiling.png" />
  </ItemGroup>
</Project>
