<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CodeImp.DoomBuilder.Plugins.NodesViewer</RootNamespace>
    <AssemblyName>NodesViewer</AssemblyName>
    <OutputPath>..\..\Build\Plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Builder.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpCompress" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Actions.cfg" />
    <EmbeddedResource Include="Resources\NodesView.png" />
  </ItemGroup>
</Project>
