name: Continuous Integration - Other

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
#        - {
#            name: "macOS",
#            os: macos-latest
#          }
        - {
            name: "Linux",
            os: ubuntu-latest
          }

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore UltimateDoomBuilder.CrossPlatform.sln

    - name: Build
      run: dotnet build UltimateDoomBuilder.CrossPlatform.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test UltimateDoomBuilder.CrossPlatform.sln --no-build --configuration Release --verbosity normal

    - name: Upload build artifacts
      if: matrix.config.name == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: "avalonia-build-${{ matrix.config.name }}"
        path: |
          Source.CrossPlatform/Core/UltimateDoomBuilder.Avalonia/bin/Release/net8.0/
        retention-days: 7
